config/routes.rb
Depot1::Application.routes.draw do
  resources :reply_topics

  resources :votes

 get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :line_items

  resources :carts

  get "store/index"
    resources :products do
    get :who_bought, :on => :member
  end

  resources :products

    root :to =>'store#index', :as => 'store'

end

app/models/reply_topic.rb
class ReplyTopic < ActiveRecord::Base
end

app/controllers/reply_topics_controller.rb
class ReplyTopicsController < ApplicationController
  # GET /reply_topics
  # GET /reply_topics.json
  def index
    @reply_topics = ReplyTopic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reply_topics }
    end
  end

  # GET /reply_topics/1
  # GET /reply_topics/1.json
  def show
    @reply_topic = ReplyTopic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply_topic }
    end
  end

  # GET /reply_topics/new
  # GET /reply_topics/new.json
  def new
    @reply_topic = ReplyTopic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply_topic }
    end
  end

  # GET /reply_topics/1/edit
  def edit
    @reply_topic = ReplyTopic.find(params[:id])
  end

  # POST /reply_topics
  # POST /reply_topics.json
  def create
    @reply_topic = ReplyTopic.new(params[:reply_topic])
    @reply_topic.uid = params[:uid]
    @reply_topic.pid = params[:pid]
    @reply_topic.name = User.find(params[:uid]).name
    @reply_topic.vote_num = 0

    respond_to do |format|
      if @reply_topic.save
        format.html { redirect_to @reply_topic, notice: 'Click edit to fill your content' }
        format.json { render json: @reply_topic, status: :created, location: @reply_topic }
      else
        format.html { render action: "new" }
        format.json { render json: @reply_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reply_topics/1
  # PUT /reply_topics/1.json
  def update
    @reply_topic = ReplyTopic.find(params[:id])

    respond_to do |format|
      if @reply_topic.update_attributes(params[:reply_topic])
        format.html { redirect_to @reply_topic, notice: 'Reply topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reply_topics/1
  # DELETE /reply_topics/1.json
  def destroy
    @reply_topic = ReplyTopic.find(params[:id])
    @reply_topic.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reply_topics_helper.rb
module ReplyTopicsHelper
end

app/views/reply_topics/_form.html.erb
<%= form_for(@reply_topic) do |f| %>
  <% if @reply_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply_topic.errors.count, "error") %> prohibited this reply_topic from being saved:</h2>

      <ul>
      <% @reply_topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reply_topics/edit.html.erb
<h1>Editing reply_topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply_topic %> |
<%= link_to 'Back', reply_topics_path %>

app/views/reply_topics/index.html.erb
<h1>Listing reply_topics</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Pid</th>
    <th>Title</th>
    <th>Vote num</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reply_topics.each do |reply_topic| %>
  <tr>
    <td><%= reply_topic.uid %></td>
    <td><%= reply_topic.pid %></td>
    <td><%= reply_topic.title %></td>
    <td><%= reply_topic.vote_num %></td>
    <td><%= reply_topic.content %></td>
    <td><%= link_to 'Show', reply_topic %></td>
    <td><%= link_to 'Edit', edit_reply_topic_path(reply_topic) %></td>
    <td><%= link_to 'Destroy', reply_topic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply topic', new_reply_topic_path %>

app/views/reply_topics/new.html.erb
<h1>New reply_topic</h1>

<%= render 'form' %>

<%= link_to 'Back', reply_topics_path %>

app/views/reply_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @reply_topic.uid %>
</p>

<p>
  <b>Pid:</b>
  <%= @reply_topic.pid %>
</p>

<p>
  <b>Title:</b>
  <%= @reply_topic.title %>
</p>

<p>
  <b>Vote num:</b>
  <%= @reply_topic.vote_num %>
</p>

<p>
  <b>Content:</b>
  <%= @reply_topic.content %>
</p>


<%= link_to 'Edit', edit_reply_topic_path(@reply_topic) %> |
<%= link_to 'Back', reply_topics_path %>