config/routes.rb
Depot1::Application.routes.draw do
  resources :reply_topics

  resources :votes

 get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :line_items

  resources :carts

  get "store/index"
    resources :products do
    get :who_bought, :on => :member
  end

  resources :products

    root :to =>'store#index', :as => 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :votes

     validates :title, :description,:presence => true
    # validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
     validates :title, :uniqueness => true
    # validates :image_url, :format => {
     #    :with => %r{\.(gif|jpg|png)$}i,
     #    :message => 'must be a URL for GIF, JPG or PNG image.'
#}

   def self.search(col_type,col_name)
       if col_type == "name"
           Product.find(:all, :conditions => ['Name LIKE ?', "%#{col_name}%"])
       elsif col_type == "description"
           Product.find(:all, :conditions => ['description LIKE ?', "%#{col_name}%"])
       elsif  col_type == "name" &&  col_type == "description"
           Product.find(:all, :conditions => ['description LIKE ?', "%#{col_name}% and ",'Name LIKE ?', "%#{col_name}%" ])
       end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    if params[:type] == "name" ||  params[:type] == "description"
     if  params[:type] == "name"
          @products = Product.search(params[:type], params[:name])
     elsif params[:type] == "description"
          @products = Product.search(params[:type], params[:description])
     end
  else
     @products = Product.all
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    user = User.find(session[:user_id])
    @product.name = user.name
    @product.uid = session[:user_id]
    @product.vote_num = 0

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,:rows=> 6 %>
  </div>

  <div class="actions">
    <%= f.submit("Post a Question") %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
    <h1>Listing posts</h1>

      <form id = 'search'>
    <%=form_tag products_path :method => 'get' do %>
           <fieldset style="width:75.5%">
              <legend>Search for</legend>

              <div>
                  <label for="name">Name:</label>

                  <%= check_box_tag :type, params[:type]= 'name' %>

                  <%= text_field_tag :name, params[:name] %>
              </div>

              <div>
                  <label for="description">Content:</label>
                  <%= check_box_tag :type, params[:type]= 'description' %>

                  <%= text_field_tag :description, params[:description] %>
              </div>

              <div>
                  <%= submit_tag "search" %>
              </div>
              </fieldset>
      <% end %>
      </form>

<% @products.sort!{ |a,b| (b.vote_num)*24*60*60 + ((b.created_at) - Time.now) <=> (a.vote_num)*24*60*60 + ((a.created_at) - Time.now) }%>
<% @products.each do |product| %>
<table>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_description">
        <dl>
            <dt><%= product.title %></dt>
            <dt>Name:<%= product.name %></dt>
            <dd><%= truncate(strip_tags(product.description),
                    :length => 80) %></dd>
        </dl>
    <%  if session[:user_id] %>
    <%  if User.find(session[:user_id]).admin == 1 %>
    <%= button_to "delete topic", product, :method=>:delete, :class=>:destroy %>
    <% end %>
    <% end %>
    <%= button_to "Vote This", votes_url(:pid => product.id, :uid => session[:user_id], :sub_level => 0),:action => "create" %>
    <%= button_to "Reply", reply_topics_url(:pid => product.id, :uid => session[:user_id]),:action => "create" %>
    </td>
    <td class="list_actions">
    <%= link_to 'Show', product %><br/>
    <%= link_to 'Edit', edit_product_path(product) %><br/>
    <tag>Vote number: <%= product.vote_num %></tag>
    </td>
    </tr>


    <% @reply=ReplyTopic.find(:all, :conditions => ["pid = '#{product.id}' "]) %>
    <% @sub_level = 1 %>
    <% @reply.each do |reply| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
            <dl>
                <dt>Reply <%= product.title %>: <%= reply.title %></dt>
                <dt>Name:<%= reply.name %></dt>
                <dd><%= truncate(strip_tags(reply.content),
                        :length => 80) %></dd>
            </dl>
        <%  if session[:user_id] %>
        <%  if User.find(session[:user_id]).admin == 1 %>
        <%= button_to "delete reply", reply, :method=>:delete, :class=>:destroy %>
        <% end %>
        <% end %>
        <%= button_to "Vote This", votes_url(:pid => product.id, :uid => session[:user_id],:rid =>reply.id ,:sub_level => @sub_level),:action => "create" %>
        </td>
        <td class="list_actions">
        <tag>Vote number: <%= reply.vote_num %></tag>
        </td>
        </tr>
    <% @sub_level = @sub_level + 1 %>
    <% end %>
 </table>
 <br> </br>
 <br> </br>
<% end %>

</div>
<br />
<%= link_to 'Post a Question ', new_product_path %>

app/views/products/new.html.erb
<h1>Post a Question</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>