config/routes.rb
Depot1::Application.routes.draw do
  resources :reply_topics

  resources :votes

 get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :line_items

  resources :carts

  get "store/index"
    resources :products do
    get :who_bought, :on => :member
  end

  resources :products

    root :to =>'store#index', :as => 'store'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to:product
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])
    @vote.pid = params[:pid]
    @vote.uid = params[:uid]
    @vote.sub_level = params[:sub_level]

    if(@vote.sub_level == 0)
        @product = Product.find(@vote.pid)
    else
        @product = ReplyTopic.find(params[:rid])
    end

    if(@product.uid != @vote.uid)

      @Old_Vote = Vote.find(:all, :conditions => ["pid = '#{@vote.pid}' and uid = '#{@vote.uid}' and sub_level = '#{@vote.sub_level}' "])

      if @Old_Vote.empty?

        @product.vote_num =  @product.vote_num + 1
        @product.update_attributes(params[:product])

        respond_to do |format|
          if @vote.save
            format.html { redirect_to @vote, notice: 'Thanks for voting.' }
            format.json { render json: @vote, status: :created, location: @vote }
          else
            format.html { render action: "new" }
            format.json { render json: @vote.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to products_path, notice: 'Already vote for this topic'
      end

    else
        redirect_to products_path, notice: 'Can not vote yourself.'
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :pid %><br />
    <%= f.text_field :pid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Pid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.uid %></td>
    <td><%= vote.pid %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @vote.uid %>
</p>

<p>
  <b>Pid:</b>
  <%= @vote.pid %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>